"""Add UserGroup model and user permissions

Revision ID: 032cd001e02b
Revises: 5419b7ff722a
Create Date: 2026-06-07 21:12:25.156155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032cd001e02b'
down_revision: Union[str, Sequence[str], None] = '5419b7ff722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_dn', sa.String(length=500), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('start_balance', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_group_dn')
    )
    op.create_index(op.f('ix_user_groups_name'), 'user_groups', ['name'], unique=True)
    op.add_column('users', sa.Column('permissions', sa.Text(), nullable=True))
    op.execute("UPDATE users SET permissions = 'chat' WHERE permissions IS NULL")
    op.alter_column('users', 'permissions', nullable=False)
    op.add_column('users', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'permissions')
    op.drop_index(op.f('ix_user_groups_name'), table_name='user_groups')
    op.drop_table('user_groups')
    # ### end Alembic commands ###
