"""add_admin_role_to_users

Revision ID: 2f821ab49813
Revises: 943ce26f1ef3
Create Date: 2026-06-08 21:53:47.206863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f821ab49813'
down_revision: Union[str, Sequence[str], None] = '943ce26f1ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_role', sa.String(length=20), server_default="none", nullable=False))
    op.add_column('users', sa.Column('admin_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_users_admin_group', 'users', 'user_groups', ['admin_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_admin_group', 'users', type_='foreignkey')
    op.drop_column('users', 'admin_group_id')
    op.drop_column('users', 'admin_role')
    # ### end Alembic commands ###
