"""add user profile fields

Revision ID: 41198292a798
Revises: d90d7acf53d3
Create Date: 2026-06-08 13:19:16.148380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41198292a798'
down_revision: Union[str, Sequence[str], None] = 'd90d7acf53d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_system_prompt', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'default_system_prompt')
    # ### end Alembic commands ###
