"""add source_generation_id

Revision ID: 4b2f3a9ab6c3
Revises: fd9f90364766
Create Date: 2026-06-08 18:59:32.116078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2f3a9ab6c3'
down_revision: Union[str, Sequence[str], None] = 'fd9f90364766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_records', sa.Column('source_generation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generation_records', 'generation_records', ['source_generation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_records', type_='foreignkey')
    op.drop_column('generation_records', 'source_generation_id')
    # ### end Alembic commands ###
