"""Add auth_source to users

Revision ID: 764afd617f07
Revises: 9937e73083bf
Create Date: 2026-06-08 17:53:17.911979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764afd617f07'
down_revision: Union[str, Sequence[str], None] = '9937e73083bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('auth_source', sa.String(length=50), server_default='local', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_source')
    # ### end Alembic commands ###
