"""Add ondelete CASCADE to chat_messages.session_id

Revision ID: 9937e73083bf
Revises: 41198292a798
Create Date: 2026-06-08 17:38:38.576954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9937e73083bf'
down_revision: Union[str, Sequence[str], None] = '41198292a798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
