"""add_cascade_delete_chat_queue_session

Revision ID: d6c260c01e9f
Revises: 87042875ea58
Create Date: 2026-06-10 07:47:28.876768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c260c01e9f'
down_revision: Union[str, Sequence[str], None] = '87042875ea58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_queue_session_id_fkey', 'chat_queue', type_='foreignkey')
    op.create_foreign_key(None, 'chat_queue', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_queue', type_='foreignkey')
    op.create_foreign_key('chat_queue_session_id_fkey', 'chat_queue', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
