"""add_deleted_at_to_generation_records

Revision ID: fd9f90364766
Revises: 764afd617f07
Create Date: 2026-06-08 18:31:58.873302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9f90364766'
down_revision: Union[str, Sequence[str], None] = '764afd617f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_records', 'deleted_at')
    # ### end Alembic commands ###
